"use client";
import { useEffect, useState } from "react";
import { useUser } from "@clerk/nextjs";
import type { SymptomLog, CycleEvent } from "@/lib/db";
import { analyzeFlags } from "@/lib/flags";
import { computeCyclePrediction } from "@/lib/cycle";

const SYMPTOM_LABELS: Record<string, string> = {
  cramps:            "Cramps",
  bloating:          "Bloating",
  headache:          "Headache",
  fatigue:           "Fatigue",
  back_pain:         "Back pain",
  mood_swings:       "Mood swings",
  nausea:            "Nausea",
  breast_tenderness: "Breast tenderness",
  acne:              "Acne",
  insomnia:          "Insomnia",
};

function buildReport(
  logs: SymptomLog[],
  cycleEvents: CycleEvent[],
  prediction: ReturnType<typeof computeCyclePrediction>
): string {
  const flags = analyzeFlags(logs);
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const symptomCounts: Record<string, number> = {};
  for (const log of logs) {
    for (const s of log.symptoms) {
      symptomCounts[s] = (symptomCounts[s] || 0) + 1;
    }
  }
  const topSymptoms = Object.entries(symptomCounts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5)
    .map(([id, count]) => `  - ${SYMPTOM_LABELS[id] ?? id}: ${count} times`)
    .join("\n");

  const heavyDays = logs.filter((l) => l.flow_level === "heavy").length;
  const mediumDays = logs.filter((l) => l.flow_level === "medium").length;
  const lightDays = logs.filter((l) => l.flow_level === "light").length;

  const recentLogs = logs.slice(0, 10).map((l) => {
    const syms = l.symptoms.map((s) => SYMPTOM_LABELS[s] ?? s).join(", ") || "None";
    const flow = l.flow_level && l.flow_level !== "none" ? `, Flow: ${l.flow_level}` : "";
    const notes = l.notes ? `, Notes: ${l.notes}` : "";
    return `  ${l.date}: ${syms}${flow}${notes}`;
  }).join("\n");

  const flagSection = flags.length > 0
    ? flags.map((f) => `  [${f.severity.toUpperCase()}] ${f.name}: ${f.summary}`).join("\n")
    : "  No significant patterns flagged.";

  const cycleSection = prediction
    ? `Average cycle length: ${prediction.avgCycleLength} days\nAverage period duration: ${prediction.avgPeriodDuration} days\nPredicted next period: ${prediction.predictedStart}`
    : "Not enough cycle data for prediction (need 2+ period start markers).";

  return `FLOW PERIOD TRACKER — CLINICAL SUMMARY
Generated: ${date}
Total logged days: ${logs.length}

CYCLE INFORMATION
${cycleSection}

FLOW LEVELS (last ${logs.length} days)
  Heavy: ${heavyDays} days | Medium: ${mediumDays} days | Light: ${lightDays} days

TOP SYMPTOMS (all time)
${topSymptoms || "  No symptoms logged."}

HEALTH PATTERNS FLAGGED
${flagSection}

RECENT LOG (last 10 entries)
${recentLogs || "  No entries."}

---
This report was generated by the Flow period tracker app.
Please share with your healthcare provider as supporting information.`;
}

export default function DoctorPage() {
  const { isSignedIn, isLoaded } = useUser();
  const [logs, setLogs] = useState<SymptomLog[]>([]);
  const [cycleEvents, setCycleEvents] = useState<CycleEvent[]>([]);
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!isSignedIn) return;
    Promise.all([
      fetch("/api/symptoms").then((r) => r.json()),
      fetch("/api/cycle").then((r) => r.json()),
    ]).then(([l, c]) => {
      setLogs(Array.isArray(l) ? l : []);
      setCycleEvents(Array.isArray(c) ? c : []);
    }).finally(() => setLoading(false));
  }, [isSignedIn]);

  const prediction = computeCyclePrediction(cycleEvents);
  const flags = analyzeFlags(logs);

  const symptomCounts: Record<string, number> = {};
  for (const log of logs) {
    for (const s of log.symptoms) {
      symptomCounts[s] = (symptomCounts[s] || 0) + 1;
    }
  }
  const topSymptoms = Object.entries(symptomCounts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5);

  const heavyDays = logs.filter((l) => l.flow_level === "heavy").length;
  const mediumDays = logs.filter((l) => l.flow_level === "medium").length;
  const lightDays = logs.filter((l) => l.flow_level === "light").length;

  function copyReport() {
    const report = buildReport(logs, cycleEvents, prediction);
    navigator.clipboard.writeText(report).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  if (!isLoaded || loading) {
    return (
      <div className="flex justify-center py-20">
        <div className="w-5 h-5 rounded-full border-2 border-rose-200 border-t-rose-500 animate-spin" />
      </div>
    );
  }

  if (!isSignedIn) {
    return (
      <div className="flex flex-col items-center justify-center py-24 space-y-3 animate-fade-in">
        <p className="text-4xl">🩺</p>
        <p className="text-lg font-semibold text-gray-700">Sign in to view your doctor summary</p>
      </div>
    );
  }

  if (logs.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-24 space-y-3 animate-fade-in">
        <p className="text-4xl">🩺</p>
        <p className="text-lg font-semibold text-gray-700">No data yet</p>
        <p className="text-sm text-gray-400 text-center max-w-xs">
          Log symptoms on the Tracker page to build your clinical summary.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header */}
      <div className="flex items-start justify-between gap-4">
        <div className="space-y-1">
          <h1 className="text-2xl font-bold text-gray-900">Doctor Summary</h1>
          <p className="text-sm text-gray-400">
            A clinical overview of your data — share with your healthcare provider.
          </p>
        </div>
        <button
          onClick={copyReport}
          className={`shrink-0 px-4 py-2 rounded-xl text-sm font-semibold transition-all ${
            copied
              ? "bg-green-500 text-white"
              : "bg-rose-500 hover:bg-rose-600 text-white shadow-sm"
          }`}
        >
          {copied ? "✓ Copied!" : "Copy Report"}
        </button>
      </div>

      {/* Cycle stats */}
      <div className="bg-white rounded-2xl border border-rose-100 shadow-sm p-5 space-y-3">
        <h2 className="text-sm font-bold text-gray-800">Cycle Overview</h2>
        {prediction ? (
          <div className="grid grid-cols-2 gap-3">
            <div className="bg-rose-50 rounded-xl p-3 space-y-0.5">
              <p className="text-xs text-gray-500">Avg cycle length</p>
              <p className="text-xl font-bold text-rose-600">{prediction.avgCycleLength} days</p>
            </div>
            <div className="bg-rose-50 rounded-xl p-3 space-y-0.5">
              <p className="text-xs text-gray-500">Avg period duration</p>
              <p className="text-xl font-bold text-rose-600">{prediction.avgPeriodDuration} days</p>
            </div>
            <div className="bg-rose-50 rounded-xl p-3 space-y-0.5">
              <p className="text-xs text-gray-500">Cycles tracked</p>
              <p className="text-xl font-bold text-rose-600">
                {cycleEvents.filter((e) => e.event_type === "period_start").length}
              </p>
            </div>
            <div className="bg-rose-50 rounded-xl p-3 space-y-0.5">
              <p className="text-xs text-gray-500">Total days logged</p>
              <p className="text-xl font-bold text-rose-600">{logs.length}</p>
            </div>
          </div>
        ) : (
          <div className="grid grid-cols-2 gap-3">
            <div className="bg-rose-50 rounded-xl p-3 space-y-0.5">
              <p className="text-xs text-gray-500">Cycles tracked</p>
              <p className="text-xl font-bold text-rose-600">
                {cycleEvents.filter((e) => e.event_type === "period_start").length}
              </p>
            </div>
            <div className="bg-rose-50 rounded-xl p-3 space-y-0.5">
              <p className="text-xs text-gray-500">Total days logged</p>
              <p className="text-xl font-bold text-rose-600">{logs.length}</p>
            </div>
          </div>
        )}
        {!prediction && cycleEvents.length < 2 && (
          <p className="text-xs text-gray-400">
            Mark at least 2 period start dates on the Tracker to calculate cycle averages.
          </p>
        )}
      </div>

      {/* Flow summary */}
      <div className="bg-white rounded-2xl border border-rose-100 shadow-sm p-5 space-y-3">
        <h2 className="text-sm font-bold text-gray-800">Flow Summary</h2>
        <div className="space-y-2">
          {[
            { label: "Heavy flow days", count: heavyDays, color: "bg-rose-500" },
            { label: "Medium flow days", count: mediumDays, color: "bg-rose-300" },
            { label: "Light flow days", count: lightDays, color: "bg-pink-200" },
          ].map((row) => (
            <div key={row.label} className="flex items-center gap-3">
              <span className="text-xs text-gray-500 w-36 shrink-0">{row.label}</span>
              <div className="flex-1 bg-gray-100 rounded-full h-2 overflow-hidden">
                <div
                  className={`h-2 rounded-full ${row.color}`}
                  style={{ width: `${Math.min(100, (row.count / logs.length) * 100)}%` }}
                />
              </div>
              <span className="text-xs font-semibold text-gray-700 w-6 text-right">{row.count}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Top symptoms */}
      {topSymptoms.length > 0 && (
        <div className="bg-white rounded-2xl border border-rose-100 shadow-sm p-5 space-y-3">
          <h2 className="text-sm font-bold text-gray-800">Most Frequent Symptoms</h2>
          <div className="space-y-2">
            {topSymptoms.map(([id, count]) => (
              <div key={id} className="flex items-center justify-between">
                <span className="text-sm text-gray-700">{SYMPTOM_LABELS[id] ?? id}</span>
                <div className="flex items-center gap-2">
                  <div className="w-24 bg-gray-100 rounded-full h-1.5 overflow-hidden">
                    <div
                      className="h-1.5 rounded-full bg-rose-400"
                      style={{ width: `${Math.min(100, (count / logs.length) * 100)}%` }}
                    />
                  </div>
                  <span className="text-xs text-gray-500 w-16 text-right">
                    {count}× ({Math.round((count / logs.length) * 100)}% of days)
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Health flags */}
      <div className="bg-white rounded-2xl border border-rose-100 shadow-sm p-5 space-y-3">
        <div className="flex items-center gap-2">
          <h2 className="text-sm font-bold text-gray-800">Flagged Health Patterns</h2>
          {flags.length > 0 && (
            <span className="text-xs bg-rose-100 text-rose-600 px-2 py-0.5 rounded-full font-medium">
              {flags.length}
            </span>
          )}
        </div>
        {flags.length === 0 ? (
          <p className="text-sm text-gray-400">
            No significant patterns flagged yet. Keep logging to build a clearer picture.
          </p>
        ) : (
          <div className="space-y-3">
            {flags.map((flag) => (
              <div
                key={flag.id}
                className="rounded-xl border border-rose-100 p-3 space-y-1.5"
              >
                <div className="flex items-center gap-2">
                  <span>{flag.icon}</span>
                  <span className="text-sm font-semibold text-gray-800">{flag.name}</span>
                  <span className={`ml-auto text-[10px] font-semibold px-2 py-0.5 rounded-full ${
                    flag.severity === "discuss"
                      ? "bg-rose-100 text-rose-600"
                      : "bg-amber-100 text-amber-600"
                  }`}>
                    {flag.severity === "discuss" ? "Discuss with doctor" : "Monitor"}
                  </span>
                </div>
                <p className="text-xs text-gray-600">{flag.summary}</p>
                <p className="text-xs text-gray-400 italic">
                  Why it&apos;s often missed: {flag.why_overlooked}
                </p>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Recent entries */}
      <div className="bg-white rounded-2xl border border-rose-100 shadow-sm p-5 space-y-3">
        <h2 className="text-sm font-bold text-gray-800">Recent Entries (last 10)</h2>
        <div className="space-y-1">
          {logs.slice(0, 10).map((log) => (
            <div
              key={log.id}
              className="flex items-start gap-3 py-2 border-b border-rose-50 last:border-0"
            >
              <span className="text-xs text-gray-400 w-20 shrink-0 pt-0.5">
                {new Date(log.date + "T12:00:00").toLocaleDateString("en-US", {
                  month: "short", day: "numeric",
                })}
              </span>
              <div className="flex-1 space-y-1">
                {log.symptoms.length > 0 ? (
                  <p className="text-xs text-gray-700">
                    {log.symptoms.map((s) => SYMPTOM_LABELS[s] ?? s).join(", ")}
                  </p>
                ) : (
                  <p className="text-xs text-gray-300">No symptoms</p>
                )}
                {log.notes && (
                  <p className="text-xs text-gray-400 italic">{log.notes}</p>
                )}
              </div>
              {log.flow_level && log.flow_level !== "none" && (
                <span className="text-xs text-rose-500 capitalize shrink-0 pt-0.5">{log.flow_level}</span>
              )}
            </div>
          ))}
        </div>
      </div>

      <p className="text-xs text-gray-300 text-center pb-2">
        Flow does not provide medical advice. Share this summary with a qualified healthcare provider.
      </p>
    </div>
  );
}
